[VARIABLES]
h2_rate = 10
pci_rate = 25
h2_temp = 600 
weight_MSE_ini = 0
###########################################################
global_price_pci_rate_ini    = 0.3
global_price_ngi_rate_ini    = 0.055
global_price_coke_rate_ini   = 0.45       
global_price_wind_rate_ini   = 0.1
global_price_o2_volfract_ini = 1
###########################################################